// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlErRKNlI0Paxb-1g-QKoV8EsioSlJlUE',
    appId: '1:691445730086:web:ce83b5ec3a6586fe3fcfe7',
    messagingSenderId: '691445730086',
    projectId: 'privtalk-4f668',
    authDomain: 'privtalk-4f668.firebaseapp.com',
    storageBucket: 'privtalk-4f668.firebasestorage.app',
    measurementId: 'G-5H9PX3DZK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4pT_pM4QoxJZhcwpaqvqNXyOu8rvAVwk',
    appId: '1:691445730086:android:19a7d0289acc91cb3fcfe7',
    messagingSenderId: '691445730086',
    projectId: 'privtalk-4f668',
    storageBucket: 'privtalk-4f668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB6p_8lIHJWD-34XBqoOaI53Pcrvr90M8',
    appId: '1:691445730086:ios:33b9600984632de43fcfe7',
    messagingSenderId: '691445730086',
    projectId: 'privtalk-4f668',
    storageBucket: 'privtalk-4f668.firebasestorage.app',
    iosBundleId: 'com.example.privtalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB6p_8lIHJWD-34XBqoOaI53Pcrvr90M8',
    appId: '1:691445730086:ios:33b9600984632de43fcfe7',
    messagingSenderId: '691445730086',
    projectId: 'privtalk-4f668',
    storageBucket: 'privtalk-4f668.firebasestorage.app',
    iosBundleId: 'com.example.privtalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlErRKNlI0Paxb-1g-QKoV8EsioSlJlUE',
    appId: '1:691445730086:web:b3441c88f45e51713fcfe7',
    messagingSenderId: '691445730086',
    projectId: 'privtalk-4f668',
    authDomain: 'privtalk-4f668.firebaseapp.com',
    storageBucket: 'privtalk-4f668.firebasestorage.app',
    measurementId: 'G-CRZ1JZTF78',
  );
}
